# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
	echo I am provisioning...
	echo "inline script" >> /home/vagrant/log.txt
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provider "vmware_workstation" do |v|
    v.gui = true
	v.memory = 2048
  end
  config.vm.provision :shell, inline: "echo 'inline command' >> /home/vagrant/log.txt"
  config.vm.provision "shell", inline: $script
  config.vm.provision :shell, path: "bootstrap.sh"
end
